---
kind: pipeline
name: default

clone:
  depth: 1

steps:
  - name: render
    image: node:11.14.0
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_CONFIG:
        from_secret: ssh_config
      GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    commands:
      - mkdir /root/.ssh && echo -n "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - mkdir .deploy_git && git clone --depth 1 --single-branch -b master git@github.com:yakumioto/yakumioto.github.io.git .deploy_git
      - export TZ='Asia/Shanghai'
      - git config --global user.email "yaku.mioto@gmail.com"
      - git config --global user.name "yakumioto"
      - ./node_modules/.bin/hexo clean
      - ./node_modules/.bin/hexo d -g
  - name: sendmsg
    image: yakumioto/drone-serverchan
    settings:
      key:
        from_secret: serverchan_key
      text: 网站更新成功

trigger:
  branch:
    - master