---
pipeline:
  renders:
    image: node:latest
    commands:
      - mkdir /root/.ssh && echo $SSH_KEY > /root/.ssh/id_rsa && echo $SSH_CONFIG > /root/.ssh/config && chmod 0600 /root/.ssh/id_rsa 
      - export TZ='Asia/Shanghai'
      - npm install hexo-cli -g
      - git config --global user.email "yaku.mioto@gmail.com"
      - git config --global user.name "yakumioto"
      - hexo clean
      - hexo d -g
    secrets: [ ssh_key, ssh_config ]
    