baseURL: 'https://mioto.me'
languageCode: zh
defaultContentLanguage: zh
title: 一只麻酱
theme: PaperMod
enableRobotsTXT: true
paginate: 10

permalinks:
  post: "/:year/:month/:filename"

googleAnalytics: "UA-102233768-1"

menu:
  main:
    - identifier: archives
      name: Archive
      url: /archives/
    - identifier: search
      name: Search
      url: /search/

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

disqusShortname: yakumioto

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 一只麻酱
  description: "我们都期待自己的存在是特殊的，到头来却平凡不已。"
  keywords: ["一只麻酱", "Mioto's Blog", "Mioto", "Yaku Mioto", "Mioto Yaku", "yakumioto"]
  author: 'Mioto Yaku'
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  comments: false

  homeInfoParams:
    Title: "银翼杀手 2049"
    Content: 我们都期待自己的存在是特殊的，到头来却平凡不已。

  socialIcons:
    - name: twitter
      url: "https://twitter.com/yakumioto"
    - name: github
      url: "https://github.com/yakumioto"
    - name: telegram
      url: "https://t.me/yakumioto"

  # ShowReadingTime: true
  # ShowShareButtons: true
  # ShowPostNavLinks: true
  # ShowBreadCrumbs: true
  # ShowCodeCopyButtons: true
  # ShowWordCount: true
  # ShowRssButtonInSectionTermList: true
  # UseHugoToc: true
  # disableSpecial1stPost: false
  # disableScrollToTop: false
  # hidemeta: false
  # hideSummary: false
  # showtoc: false
  # tocopen: false
