menu:
    Blog: /
    Archive: /archives/
    contact: /contact/
    Twitter: https://twitter.com/yakumioto
    GitHub: https://github.com/yakumioto
    Rss: /atom.xml

favicon: /favicon.png

# Comment
# e.g disqus: seansun
# disqus: yakumioto

# Analytics
# google-analytics:
ga: UA-102233768-1

# Copyright Infomation
startyear: 2017
