name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and deploy
        run: |
          export TZ='Asia/Shanghai'
          git config --global user.email "yaku.mioto@gmail.com"
          git config --global user.name "yakumioto"
          git submodule update --init
          mkdir .deploy_git
          git clone --depth 1 --single-branch -b master https://x-access-token:463b2dfcb9ae55fdd9a16b8aa502d1adee61bb34@github.com/yakumioto/yakumioto.github.io.git .deploy_git
          npm install
          ./node_modules/.bin/hexo clean
          ./node_modules/.bin/hexo d -g
      - name: sending msg
        uses: yakumioto/serverchan-action@v1
        with:
          key: SCU48558T164ff96a3316d8a22cacea21de21866b5caed80baa044
          text: 网站部署成功!
