name: Deploy

on: 
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
      - name: Build
        run: hugo --minify
      
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
      - name: sending msg
        uses: yakumioto/serverchan-action@v1
        with:
          key: ${{ secrets.GITHUB_SERVERCHAN_KEY }}
          text: 网站部署成功!
